name: CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      bb-run:
        description: 'Building Block Run Object'
        required: true

jobs:
  parse-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse JSON input
        id: parse_json
        run: |
          echo "Received JSON: ${{ github.event.inputs.config }}"
          echo "Parsed Value 1: $(echo '${{ github.event.inputs.config }}' | jq -r .key1)"
          echo "Parsed Value 2: $(echo '${{ github.event.inputs.config }}' | jq -r .key2)"

      # You can use parsed values in subsequent steps
      - name: Use Parsed Values
        run: |
          value1=$(echo '${{ github.event.inputs.config }}' | jq -r .key1)
          echo "Using parsed value1: $value1"